# permissions for end users to view opdemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opdemo-viewer-role
rules:
- apiGroups:
  - opdemo.opdemo.org
  resources:
  - opdemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opdemo.opdemo.org
  resources:
  - opdemoes/status
  verbs:
  - get
