
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - opdemo.opdemo.org
  resources:
  - opdemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opdemo.opdemo.org
  resources:
  - opdemoes/status
  verbs:
  - get
  - patch
  - update
